### ISSUE TITLE
Gatsby cannot load SVGs in Windows environment

### ISSUE THREAD

**Issue by salikansari6** [proceduretech/website#28]
To reproduce error, run the project in a Windows Environment and go to "/team" route
![image](https://user-images.githubusercontent.com/72390270/150559398-8dff0f3f-8da3-459f-99b5-ce6a192f05e7.png)

**Comment by salikansari6** [comment]
FIX: Change the gatsby-plugin-react-svg config in ```gatsby.config.js```.
```
{
      resolve: 'gatsby-plugin-react-svg',
      options: {
        rule: {
          include: /images\/.*\.svg/
        }
      }
    }
```
Current path regex only matches for OSX and Linux systems, change it to,
```
 {
      resolve: 'gatsby-plugin-react-svg',
      options: {
        rule: {
          include: /images(\/|\\).*\.svg/
        }
      }
    }
```

**Comment by rajvaya** [comment]
This issue is already solved take code from develop branch and work for reference  see the openings section where i have used SVGs

**Comment by raveracker** [comment]
@salikansari6 Why don't you create a PR and pin it on this issue and close this

**Comment by salikansari6** [comment]
Fix:
https://github.com/proceduretech/website/pull/31
